# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-02 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=80, verbose_name='Título')),
                ('slug', models.SlugField(max_length=100, verbose_name='Identificador')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('criada', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('modificada', models.DateTimeField(auto_now=True, verbose_name='Modificada em')),
            ],
            options={
                'verbose_name': 'Notícia',
                'verbose_name_plural': 'Notícias',
                'ordering': ['titulo'],
            },
        ),
    ]
