# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-02 05:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['titulo'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
